.PHONY: install install-dev lint test run

install:
	poetry install

install-dev:
	poetry install --with dev
	poetry run pre-commit install || true

lint:
	poetry run black --check .
	poetry run flake8 .

test:
	poetry run pytest -q

run-mock:
	poetry run python -m src.core.app --backend mock
